services:
  graphql.playground:
    image: graphql.playground
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "!sqlTest201"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"